### ISSUE TITLE
Usage on lambda leads to panic inside stack trace parser

### ISSUE THREAD

**Issue by mateusz** [kaeuferportal/raygun4go#28]
My usage:

```go
func Handler(ctx context.Context, ev events.CloudWatchEvent) (string, error) {
	if raygunKey != "" {
		raygun, err := raygun4go.New("yyy", raygunKey)
		if err != nil {
			return "Error in raygun4go.New", err
		}
		raygun.Version(stage)

		defer raygun.HandleError()
		raygun.CreateError("test2") 
	}
}
```

Results in the following:

```json
{
    "errorMessage": "runtime error: index out of range [1] with length 1",
    "errorType": "boundsError",
    "stackTrace": [
        {
            "path": "github.com/aws/aws-lambda-go@v1.17.0/lambda/function.go",
            "line": 36,
            "label": "(*Function).Invoke.func1"
        },
        {
            "path": "runtime/panic.go",
            "line": 679,
            "label": "gopanic"
        },
        {
            "path": "runtime/panic.go",
            "line": 75,
            "label": "goPanicIndex"
        },
        {
            "path": "github.com/kaeuferportal/stack2struct@v0.0.0-20150211121835-6838fbadc918/stack2struct.go",
            "line": 80,
            "label": "extractLineNumberAndFile"
        },
        {
            "path": "github.com/kaeuferportal/stack2struct@v0.0.0-20150211121835-6838fbadc918/stack2struct.go",
            "line": 54,
            "label": "Parse"
        },
        {
            "path": "github.com/kaeuferportal/stack2struct@v0.0.0-20150211121835-6838fbadc918/stack2struct.go",
            "line": 36,
            "label": "Current"
        },
        {
            "path": "github.com/!mindscape!h!q/raygun4go@v0.0.0-20180117220438-5c22b2306e04/request_data.go",
            "line": 81,
            "label": "currentStack"
        },
        {
            "path": "github.com/!mindscape!h!q/raygun4go@v0.0.0-20180117220438-5c22b2306e04/raygun4go.go",
            "line": 212,
            "label": "(*Client).CreateError"
        },
        {
            "path": "taekai/main.go",
            "line": 73,
            "label": "Handler"
        },
        {
            "path": "reflect/value.go",
            "line": 460,
            "label": "Value.call"
        },
        {
            "path": "reflect/value.go",
            "line": 321,
            "label": "Value.Call"
        },
        {
            "path": "github.com/aws/aws-lambda-go@v1.17.0/lambda/handler.go",
            "line": 124,
            "label": "NewHandler.func1"
        },
        {
            "path": "github.com/aws/aws-lambda-go@v1.17.0/lambda/handler.go",
            "line": 24,
            "label": "lambdaHandler.Invoke"
        },
        {
            "path": "github.com/aws/aws-lambda-go@v1.17.0/lambda/function.go",
            "line": 69,
            "label": "(*Function).Invoke"
        },
        {
            "path": "reflect/value.go",
            "line": 460,
            "label": "Value.call"
        },
        {
            "path": "reflect/value.go",
            "line": 321,
            "label": "Value.Call"
        },
        {
            "path": "net/rpc/server.go",
            "line": 377,
            "label": "(*service).call"
        },
        {
            "path": "runtime/asm_amd64.s",
            "line": 1357,
            "label": "goexit"
        }
    ]
}
```

Note I have also tried moving raygun init into "init", with no change to the outcome. Also, I tried using "defer raygun.HandleError()" and "panic", just to test, with the same result.

**Comment by QuantumNightmare** [comment]
Hi Mateusz,

Thanks for raising this issue. Looking at the stack trace, it appears that the Raygun4Go package you are using is trying to use the actual kaeuferportal/stack2struct code. Which you can see here doesn't have any bounds checking when parsing the stack trace lines: https://github.com/kaeuferportal/stack2struct/blob/master/stack2struct.go#L80

Raygun4Go should be using its own version of this stack trace parsing code which adds in bounds checking which you can see in this repository: https://github.com/MindscapeHQ/raygun4go/blob/master/stack2struct.go#L89

From your stack trace, line 212 of raygun4go.go does not line up with the method name mentioned in the stack trace, which makes me further wonder if you've got an older version of Raygun4Go. The latest version is 1.1.0, and the stack trace parsing bug should have been fixed in 1.0.0 as it came out of beta.

You can check which version of raygun4go you're using by viewing an exception in the Raygun app, going to the "raw" tab and looking for the version of the client section. That is assuming the stacktrace you posted above does make it to the Raygun app. If you're having trouble looking this up, you can send me the app id that appears in the url while looking at exceptions in the Raygun app, it looks like a small string usually with both numbers and letters.

**Comment by mateusz** [comment]
Oooh this is such a facepalm moment - looks like i've had some outdated dependency installed that made it into my go.mod.

Can confirm this works completely fine once the dependency is upgraded to latest via `go get -u github.com/MindscapeHQ/raygun4go` and `go mod tidy`.

Thank you very much for prompt response, and I have learned something new in the process too.

**Comment by QuantumNightmare** [comment]
No worries! Glad to hear that this was the case and you were able to get things working easily enough :)
